import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { AppProps } from 'next/app';
import Head from "next/head";
import "../styles/root.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MyApp({ Component, pageProps }: AppProps) {
  // Component is the active page
  // pageProps is an object with the initial props for that page

  return (
    <html lang="en">
      <Head>
        {(process.env.NEXT_PUBLIC_NO_INDEX === "true" || process.env.NEXT_PUBLIC_ENVIRONMENT === "development") ? (
          <meta name="robots" content="noindex, nofollow" />
        ) : null}
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Component {...pageProps} />
      </body>
    </html>
  );
}

export default MyApp;