import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/root.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { AppProps } from 'next/app';

function MyApp({ Component, pageProps }: AppProps) {
  // Component is the active page
  // pageProps is an object with the initial props for that page

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Component {...pageProps} />
      </body>
    </html>
  );
}

export default MyApp;